### ISSUE TITLE
color scheme for terminal

### ISSUE THREAD

**Issue by irasekh3** [sevenfoxes/dotfiles#1]
do you have a link to the color scheme you're using for the terminal? specifically referring to  [https://github.com/sevenfoxes/dotfiles/blob/master/ghostwheel.png](https://github.com/sevenfoxes/dotfiles/blob/master/ghostwheel.png)

**Comment by sevenfoxes** [comment]
This is for iTerm, if you don't have iTerm, it's actually just a modified version of Manjaro's breath dark theme.
[breath-fancy.zip](https://github.com/sevenfoxes/dotfiles/files/3746179/breath-fancy.zip)

**Comment by sevenfoxes** [comment]
I'm primarily a Manjaro user, but at work we're all Mac lol.
